parameters:
    cygnus_olytics.data_formatter.generic.class: Cygnus\OlyticsBundle\DataFormatter\GenericFormatter
    cygnus_olytics.events.website.request_factory.class: Cygnus\OlyticsBundle\Event\Website\WebsiteRequestFactory
    cygnus_olytics.events.website.request_manager.class: Cygnus\OlyticsBundle\Event\Website\WebsiteRequestManager
    cygnus_olytics.events.website.persistor.class: Cygnus\OlyticsBundle\Event\Website\WebsitePersistor
    cygnus_olytics.bot_detector.class: Cygnus\OlyticsBundle\Detector\BotDetector
    cygnus_olytics.aggregation_manager.class: Cygnus\OlyticsBundle\Aggregation\Manager
    cygnus_olytics.aggregation.abstract.class: Cygnus\OlyticsBundle\Aggregation\AbstractAggregation
    cygnus_olytics.aggregation.openx.class: Cygnus\OlyticsBundle\Aggregation\OpenXImpressionAggregation
    cygnus_olytics.aggregation.archive.content.class: Cygnus\OlyticsBundle\Aggregation\ContentArchiveAggregation

services:
    cygnus_olytics.bot_detector:
        class: %cygnus_olytics.bot_detector.class%
        arguments: [ @kernel ]

    cygnus_olytics.data_formatter.generic:
        class: %cygnus_olytics.data_formatter.generic.class%

    cygnus_olytics.events.website.persistor:
        class: %cygnus_olytics.events.website.persistor.class%
        arguments:
            - @doctrine_mongodb.odm.olytics_connection
            - @cygnus_olytics.index_manager
            - @cygnus_olytics.aggregation_manager
            - %cygnus_olytics.accounts%

    cygnus_olytics.events.website.request_factory:
        class: %cygnus_olytics.events.website.request_factory.class%
        arguments: [ @cygnus_olytics.data_formatter.generic]

    cygnus_olytics.events.website.request_manager:
        class: %cygnus_olytics.events.website.request_manager.class%
        arguments: [ @cygnus_olytics.events.website.request_factory, @cygnus_olytics.events.website.persistor ]

    cygnus_olytics.index_manager:
        class: Cygnus\OlyticsBundle\Index\IndexManager
        arguments: [ @doctrine_mongodb.odm.olytics_connection, @snc_redis.cache ]

    cygnus_olytics.aggregation_manager:
        class: %cygnus_olytics.aggregation_manager.class%

    cygnus_olytics.aggregation.abstract:
        abstract: true
        arguments: [ @cygnus_olytics.index_manager, @doctrine_mongodb.odm.olytics_connection ]

    cygnus_olytics.aggregation.openx:
        parent: cygnus_olytics.aggregation.abstract
        class: %cygnus_olytics.aggregation.openx.class%
        tags:
            - { name: cygnus_olytics.aggregation }

    cygnus_olytics.aggregation.archive.content:
        parent: cygnus_olytics.aggregation.abstract
        class: %cygnus_olytics.aggregation.archive.content.class%
        tags:
            - { name: cygnus_olytics.aggregation }

